Pokepedia JavaScript Group Project: Submission.
MussieTeka/JavaScript-Group-Capstone pull request #36
Opened 2023-04-21 14:49 UTC by MussieTeka

This pull request is for **Pokepedia Project**, a JavaScript group capstone project. 

The project: 

- Displays a list of Pokémon cards with their respective information.
- Includes an add-comment button that opens a popup window with additional information about the selected Pokémon.
- Uses JavaScript and two modules (itemCounter.js and commentCounter.js) to track the number of likes and comments for each card.
- Fetches additional information from the PokeAPI when a user clicks on the add-comment button.
- Includes script.js with dynamic card list and popup windows.
- Adds itemCounter.test.js with Jest tests for the counter function.
- Adds commentCounter.test.js with Jest tests for the countComments function.

All the necessary files are included in this pull request and it follows the project's requirements.

Group members:

- @ikennarichard 
- @MussieTeka 

Video preparation: https://drive.google.com/file/d/1oKX1mA35egTz2hvK8usTaErXK5PcmR-a/view?usp=sharing

Thank you for reviewing our work.

2023-04-21 15:41 UTC, divinecharlotte requested changes
Hi @Team , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- No linters errors ✔️ 
- Descriptive PR ✔️ 
- good commit messages 👍 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 15:41 UTC, divinecharlotte commented on src/script.js
> +];
- [ ] Kindly consider using the  [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270) you selected to show  the list of items on the screen not hard coding them and doing that will help you to fulfill the below requirement 
- > When the page loads, the webapp retrieves data from:
   > The selected API and shows the list of items on screen.

2023-04-22 12:53 UTC, MussieTeka commented on src/script.js
> +];
Hi @divinecharlotte, Thank you for your feedback. We updated the app to fetch data from the Poke API and display items dynamically using a loop, instead of hard-coding them in arrays. Thanks for helping us improve our code.

2023-04-22 13:05 UTC, aamirkhan2478 approved these changes
Hi @MussieTeka & @ikennarichard  , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR
✅ Well done you did all changes suggested by previous reviewer :clap: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-22 15:03 UTC, merged